ALTER TABLE ticket
ADD CONSTRAINT CHK_ticket_one_reference CHECK (
    (CASE WHEN planeID IS NOT NULL THEN 1 ELSE 0 END +
     CASE WHEN busID IS NOT NULL THEN 1 ELSE 0 END +
    CASE WHEN trainID IS NOT NULL THEN 1 ELSE 0 END) = 1
);
